//! GENERATED by tools/convert_sfx.py -- do not edit by hand.
//! CC0 sampled SFX (Kenney.nl + freesound.org, see assets/pack/CREDITS.md)
//! as SPU-ADPCM blobs with per-sample offsets and native rates.

/// One cooked sample: byte offset into the uploaded SPU bank, the
/// rate it was recorded at, and how many ADPCM blocks of real audio
/// it holds.
///
/// `blocks` excludes the self-looping silent tail every sample ends
/// with, so it is the length of the sound itself. psx-sfx times its
/// cutoff from it: without a length there is nothing to schedule and
/// a finished voice sits on the tail with a live envelope instead of
/// being silenced.
pub struct Sample {
    pub off: u32,
    pub rate: u16,
    pub blocks: u16,
}

/// WORLD.PAK chunk id of the cooked bank (streamed to SPU at boot;
/// the blob never lives in main RAM).
pub const SFX_CHUNK_ID: u32 = 3000;

pub const S_STEP_GRASS: usize = 0;
pub const S_STEP_STONE: usize = 1;
pub const S_STEP_SAND: usize = 2;
pub const S_STEP_WOOD: usize = 3;
pub const S_DIG_SOFT: usize = 4;
pub const S_DIG_STONE: usize = 5;
pub const S_DIG_WOOD: usize = 6;
pub const S_BREAK: usize = 7;
pub const S_PLACE: usize = 8;
pub const S_HURT: usize = 9;
pub const S_DOOR: usize = 10;
pub const S_CHEST: usize = 11;
pub const S_CLICK: usize = 12;
pub const S_CONFIRM: usize = 13;
pub const S_PIG: usize = 14;
pub const S_COW: usize = 15;
pub const S_SHEEP: usize = 16;
pub const S_CHICKEN: usize = 17;
pub const S_ZOMBIE: usize = 18;
pub const S_BONES: usize = 19;
pub const S_BARK: usize = 20;
pub const S_HISS: usize = 21;
pub const S_SPLASH: usize = 22;
pub const S_EAT: usize = 23;
pub const S_EXPLODE: usize = 24;

pub static SAMPLES: [Sample; 25] = [
    Sample { off: 0, rate: 22050, blocks: 234 }, // step_grass
    Sample { off: 3760, rate: 22050, blocks: 82 }, // step_stone
    Sample { off: 5088, rate: 22050, blocks: 234 }, // step_sand
    Sample { off: 8848, rate: 22050, blocks: 214 }, // step_wood
    Sample { off: 12288, rate: 22050, blocks: 127 }, // dig_soft
    Sample { off: 14336, rate: 11025, blocks: 138 }, // dig_stone
    Sample { off: 16560, rate: 11025, blocks: 86 }, // dig_wood
    Sample { off: 17952, rate: 11025, blocks: 158 }, // break
    Sample { off: 20496, rate: 22050, blocks: 127 }, // place
    Sample { off: 22544, rate: 11025, blocks: 138 }, // hurt
    Sample { off: 24768, rate: 11025, blocks: 217 }, // door
    Sample { off: 28256, rate: 11025, blocks: 97 }, // chest
    Sample { off: 29824, rate: 22050, blocks: 77 }, // click
    Sample { off: 31072, rate: 11025, blocks: 115 }, // confirm
    Sample { off: 32928, rate: 11025, blocks: 286 }, // pig
    Sample { off: 37520, rate: 11025, blocks: 375 }, // cow
    Sample { off: 43536, rate: 11025, blocks: 335 }, // sheep
    Sample { off: 48912, rate: 11025, blocks: 355 }, // chicken
    Sample { off: 54608, rate: 11025, blocks: 329 }, // zombie
    Sample { off: 59888, rate: 11025, blocks: 315 }, // bones
    Sample { off: 64944, rate: 22050, blocks: 195 }, // bark
    Sample { off: 68080, rate: 11025, blocks: 315 }, // hiss
    Sample { off: 73136, rate: 11025, blocks: 217 }, // splash
    Sample { off: 76624, rate: 11025, blocks: 157 }, // eat
    Sample { off: 79152, rate: 11025, blocks: 453 }, // explode
];
