#!/usr/bin/env python3
"""Convert the CC0 "16x16 Block Texture Set" (OpenGameArt, CC0, no attribution
required) into per-tile 16-colour CLUTs + index maps for voxide's 4bpp atlas.
Emits game/src/texdata.rs. Tiles the pack lacks stay on the procedural path."""
from PIL import Image
import os
SRC = os.path.join(os.path.dirname(__file__), "..", "assets", "pack", "blocks", "blocks")
OUT = os.path.join(os.path.dirname(__file__), "..", "game", "src", "texdata.rs")
# tile id -> (pack filename or None, alpha-composite bg, recolor)
M = {
 0:("grass_top",None,None), 1:("grass_side",None,None), 2:("dirt",None,None),
 3:("stone_generic",None,None), 4:("oak_log_top",None,None), 5:("oak_log_side",None,None),
 6:("oak_leaves",(32,56,26),"leaves"), 7:("sand_ugly_2",None,"sand"),
 9:("stone_generic_ore_nuggets",None,"coal"), 10:("stone_generic_ore_nuggets",None,"iron"),
 11:("stone_generic_ore_nuggets",None,None), 12:("stone_generic_ore_crystalline",None,None),
 14:("snow",None,None), 15:("grass_snowy_side",None,None),
 16:("cobblestone",None,None), 17:("oak_planks",None,None), 20:("mud_bricks",None,None),
}
NTILES = 32
def sat(c): return max(c)-min(c)
def recolor(pal, mode):
    if mode=="leaves":
        # Remap to Minecraft's dark warm oak-leaf green (~57,84,34): the pack's
        # leaves quantised to a washed-out cyan-green (B ~= G), reading harsh
        # and pale vs the minecraft.wiki plains reference (sampled 57,74,34).
        out=[]
        for (r,g,b) in pal:
            lum=(r+g+b)//3
            lum=58+(lum-58)//2  # halve contrast around the leaf base
            out.append((min(255,57*lum//58),min(255,84*lum//58),min(255,34*lum//58)))
        return out
    if mode=="sand":
        # Remap the whole palette to Minecraft's pale-cream sand (base ~219,207,163),
        # scaled by relative luminance (keeps the tile's structure) with the
        # contrast eased -- the pack's sand is far too orange and busy vs the
        # minecraft.wiki desert reference.
        out=[]
        for (r,g,b) in pal:
            lum=(r+g+b)//3
            lum=171+(lum-171)*2//3  # ease contrast toward the cream base
            out.append((min(255,219*lum//171),min(255,207*lum//171),min(255,163*lum//171)))
        return out
    # swap the saturated (ore-nugget) palette entries to a new colour, keep greys.
    out=[]
    for (r,g,b) in pal:
        if sat((r,g,b))>34 and r>=b:  # warm nugget
            lum=(r+g+b)//3
            if mode=="coal": out.append((max(0,lum-70),max(0,lum-66),max(0,lum-60)))
            elif mode=="iron": out.append((min(255,lum+40),int(lum*0.82),int(lum*0.6)))
            else: out.append((r,g,b))
        else: out.append((r,g,b))
    return out
def conv(fn,bg,rc):
    im=Image.open(os.path.join(SRC,fn+".png")).convert("RGBA")
    if bg is not None:
        b=Image.new("RGBA",im.size,bg+(255,)); im=Image.alpha_composite(b,im)
    im=im.convert("RGB").resize((16,16),Image.NEAREST)
    q=im.quantize(colors=16,method=Image.MEDIANCUT)
    p=q.getpalette(); p=(p+[0]*48)[:48]; pal=[(p[i*3],p[i*3+1],p[i*3+2]) for i in range(16)]
    idx=list(q.getdata())
    if rc: pal=recolor(pal,rc)
    return pal,idx
has=[False]*NTILES; pals=[[(0,0,0)]*16]*NTILES; idxs=[[0]*256]*NTILES
for t,(fn,bg,rc) in M.items():
    if fn is None: continue
    pal,idx=conv(fn,bg,rc); has[t]=True; pals[t]=pal; idxs[t]=idx
    print(f"tile {t:2d} <- {fn}")
with open(OUT,"w") as f:
    f.write("// GENERATED by tools/convert_pack.py -- do not edit.\n")
    f.write("// Source: OpenGameArt \"16x16 Block Texture Set\", CC0 (public domain, no\n")
    f.write("// attribution required). Quantised to per-tile 16-colour CLUTs for the 4bpp atlas.\n\n")
    f.write("pub const PACK_HAS: [bool; 32] = [")
    f.write(",".join("true" if h else "false" for h in has)); f.write("];\n\n")
    f.write("pub const PACK_PAL: [[(u8,u8,u8); 16]; 32] = [\n")
    for t in range(NTILES):
        f.write("  ["+",".join(f"({r},{g},{b})" for (r,g,b) in pals[t])+"],\n")
    f.write("];\n\n")
    f.write("pub const PACK_IDX: [[u8; 256]; 32] = [\n")
    for t in range(NTILES):
        f.write("  ["+",".join(str(v) for v in idxs[t])+"],\n")
    f.write("];\n")
print("wrote",OUT)
