#!/usr/bin/env python3
"""Cook assets/sfx/*.wav into SPU-ADPCM: assets/sfx/sfx.bin + game/src/sfxdata.rs.

Sources are CC0 recordings (Kenney.nl packs, freesound.org -- see
assets/pack/CREDITS.md), pre-trimmed to 22050/11025 Hz mono s16 by ffmpeg.
This script peak-normalizes, encodes PS1 SPU-ADPCM (filters 0-4, best
filter+shift per 28-sample block), appends a self-looping silent block so a
finished one-shot parks the voice on silence (the same trick the SDK tones
used), and emits the offset/rate table the game indexes by name.
"""

import struct
import sys
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "sfx"
PAK = SRC / "pak"
BIN = PAK / "chunk_3000.bin"  # WORLD.PAK payload; id must match sfxdata SFX_CHUNK_ID
RS = ROOT / "game" / "src" / "sfxdata.rs"

# Fixed order: the generated S_* consts index SAMPLES.
SOUNDS = [
    "step_grass", "step_stone", "step_sand", "step_wood",
    "dig_soft", "dig_stone", "dig_wood",
    "break", "place", "hurt", "door", "chest", "click", "confirm",
    "pig", "cow", "sheep", "chicken", "zombie", "bones", "bark", "hiss",
    "splash", "eat", "explode",
]

FILTERS = [(0, 0), (60, 0), (115, -52), (98, -55), (122, -60)]


def read_wav(path):
    with wave.open(str(path)) as w:
        assert w.getnchannels() == 1 and w.getsampwidth() == 2, path
        rate = w.getframerate()
        data = w.readframes(w.getnframes())
    samples = list(struct.unpack("<%dh" % (len(data) // 2), data))
    peak = max(1, max(abs(s) for s in samples))
    scale = 0.9 * 32767 / peak
    return rate, [int(s * scale) for s in samples]


def encode_block(block, prev1, prev2):
    """Best (filter, shift) for one 28-sample block; returns bytes + history."""
    best = None
    for f, (k0, k1) in enumerate(FILTERS):
        for shift in range(13):
            p1, p2 = prev1, prev2
            nibbles, err = [], 0
            for s in block:
                predicted = (p1 * k0 + p2 * k1) >> 6
                residual = s - predicted
                # Round-to-nearest quantize into a signed nibble.
                if shift < 12:
                    q = max(-8, min(7, (residual + (1 << (11 - shift))) >> (12 - shift)))
                else:
                    q = max(-8, min(7, residual))
                dec = (q << (12 - shift)) + predicted
                dec = max(-32768, min(32767, dec))
                nibbles.append(q & 0xF)
                err += (dec - s) * (dec - s)
                p2, p1 = p1, dec
            if best is None or err < best[0]:
                best = (err, f, shift, nibbles, p1, p2)
    _, f, shift, nibbles, p1, p2 = best
    out = bytearray(16)
    out[0] = (shift & 0xF) | (f << 4)
    out[1] = 0x00
    for i, n in enumerate(nibbles):
        if i % 2 == 0:
            out[2 + i // 2] |= n
        else:
            out[2 + i // 2] |= n << 4
    return bytes(out), p1, p2


def encode(samples):
    samples = samples + [0] * ((28 - len(samples) % 28) % 28)
    blob = bytearray()
    p1 = p2 = 0
    for i in range(0, len(samples), 28):
        block, p1, p2 = encode_block(samples[i : i + 28], p1, p2)
        blob += block
    # Self-looping silent tail: a finished voice parks here until re-keyed.
    silent = bytearray(16)
    silent[1] = 0x07  # loop start + loop end + repeat
    blob += silent
    return bytes(blob)


def main():
    blobs, table = bytearray(), []
    for name in SOUNDS:
        rate, samples = read_wav(SRC / f"{name}.wav")
        blob = encode(samples)
        table.append((name, len(blobs), len(blob), rate))
        blobs += blob
        print(f"{name:12s} {rate:5d}Hz {len(samples):6d} smp -> {len(blob):6d}B")
    PAK.mkdir(exist_ok=True)
    BIN.write_bytes(bytes(blobs))
    print(f"sfx.bin: {len(blobs)} bytes ({len(blobs)/1024:.0f} KiB SPU RAM)")

    lines = [
        "//! GENERATED by tools/convert_sfx.py -- do not edit by hand.",
        "//! CC0 sampled SFX (Kenney.nl + freesound.org, see assets/pack/CREDITS.md)",
        "//! as SPU-ADPCM blobs with per-sample offsets and native rates.",
        "",
        "/// One cooked sample: byte offset into the uploaded SPU bank, and",
        "/// the rate it was recorded at.",
        "pub struct Sample {",
        "    pub off: u32,",
        "    pub rate: u16,",
        "}",
        "",
        "/// WORLD.PAK chunk id of the cooked bank (streamed to SPU at boot;",
        "/// the blob never lives in main RAM).",
        "pub const SFX_CHUNK_ID: u32 = 3000;",
        "",
    ]
    for i, (name, _, _, _) in enumerate(table):
        lines.append(f"pub const S_{name.upper()}: usize = {i};")
    lines += ["", f"pub static SAMPLES: [Sample; {len(table)}] = ["]
    for name, off, ln, rate in table:
        lines.append(f"    Sample {{ off: {off}, rate: {rate} }}, // {name}")
    lines += ["];", ""]
    RS.write_text("\n".join(lines))
    print(f"wrote {RS.relative_to(ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
